name: Build and Push to ACR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name aimeetregistry
      - name: Build and Push Client
        run: |
          docker build \
          -t aimeetregistry.azurecr.io/meet-client \
          --build-arg REACT_APP_API_URL=http://meet-server-service:3001 \
          ./client
          docker push aimeetregistry.azurecr.io/meet-client
      - name: Build and Push Server
        run: |
          docker build -t aimeetregistry.azurecr.io/meet-server ./server
          docker push aimeetregistry.azurecr.io/meet-server